package:
  name: project_name
  version: {{ environ["GIT_DESCRIBE_TAG"] }}

source:
  path: ..

build:
  number: {{ environ.get("GIT_DESCRIBE_NUMBER", 0) }}
  string: {{ environ.get("GIT_BUILD_STR", "") }}
  noarch: python
  script: {{PYTHON}} -m pip install . -vv

requirements:
  build:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - project_name
  requires:
    - pytest

about:
  home: https://github.com/pcdshub/project-name
  license: LicenseRef-BSD-3-Clause-SLAC
  license_family: BSD
  summary: A short description of the project.
