name: PCDS Standard Testing

on:
  push:
    branches:
      - master
    paths-ignore:
  pull_request:
    branches:
      - master
  release:
    types:
      - created

jobs:
  standard:
    uses: klauer/pcds-ci-helpers/.github/workflows/python-standard.yml@enh_gha
    with:
      # The workflow needs to know the package name.  This can be determined
      # automatically if the repository name is the same as the import name.
      package-name: "project_name"
      # Extras that will be installed for both conda/pip:
      testing-extras: ""
      # Extras to be installed only for conda-based testing:
      conda-testing-extras: ""
      # Extras to be installed only for pip-based testing:
      pip-testing-extras: ""
      # Use setuptools-scm in the conda-build workflow
      use-setuptools-scm: true
